### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by rjmcguire** [StalkR/misc#5]
Hi,

Any chance of you making this client + server MIT licensed? Or perhaps BOOST licensed?

Thanks.

**Comment by rjmcguire** [comment]
Ah, I see that you have Apache license on the misc repo.
I was talking about the little remote terminal client and server in Go.

**Comment by StalkR** [comment]
Yes it's all apache licensed in misc, enjoy :)
planning to use / extend it?

**Comment by rjmcguire** [comment]
No not at the moment, I found your blog while looking for decent docs on
setting terminal to Raw. Then found that and wanted to fork for later, but
public domain / unspecified licenses are scary.

The blog post and implementation combined make a pretty good tutorial on
how SSH and remote terminals work.
And they keep it short. Which helps retaining the info.

Thanks!
